// Second batch of hand-verified seed data (2026-08-16), expanding the catalog
// toward the phase-1 target of ~60 programs. Same sourcing standard as
// seed-data.ts: verified via live web research, still needs human
// reconfirmation before being trusted long-term.
//
// Four programs turned up in research but were deliberately excluded:
// - Arizona Conservation Corps: likely a duplicate of the Conservation
//   Legacy / AZCC entry already seeded — not confirmed as a distinct program.
// - Coro Fellows Program in Public Affairs: stipends are need-based and not
//   guaranteed at most of its 5 centers (only NY guarantees a fixed amount).
// - Jesuit Volunteer Corps: ~$100/mo nominal stipend on top of in-kind cost
//   coverage — functionally a need-based-coverage program, not a paid one.
// - WorldTeach: historically fee-based (participant pays), and currently
//   paused/not accepting applications — fails both the pay and
//   operating-status bar.

import type { SeedProgram } from "./seed-data";

const TZ_ET = "America/New_York";
const TZ_CT = "America/Chicago";
const TZ_MT = "America/Denver";
const TZ_PT = "America/Los_Angeles";

const AMERICORPS_TURMOIL_NOTE =
  "AmeriCorps-affiliated; subject to the 2025-26 federal AmeriCorps funding turmoil affecting many state and regional corps (spring 2025 grant terminations, court-ordered restoration, stipends accruing unpaid during the Oct-Nov 2025 shutdown).";

export const EXPANSION_PROGRAMS: SeedProgram[] = [
  // ==================== degree_required = 0, more conservation corps ====================
  {
    slug: "idaho-conservation-corps",
    name: "Idaho Conservation Corps",
    operator: "Northwest Youth Corps",
    category: "conservation",
    summary:
      "A statewide program of Northwest Youth Corps offering paid conservation crew positions (trail work, fuels reduction, restoration) for youth and young adults across Idaho public lands. Young-adult programs are AmeriCorps-affiliated with a weekly stipend plus education award.",
    source_url: "https://idahocc.org/",
    degree_required: 0,
    min_age: 15,
    max_age: 26,
    citizenship: "us_citizen_or_lpr",
    other_eligibility: "Youth programs 15-18; young adult programs 19-26; some leadership roles require 20+. Must be able to hike with a pack and camp in backcountry settings.",
    pay_type: "weekly",
    pay_low: 32500,
    pay_high: 32500,
    pay_note: "$325/week plus $650 travel stipend confirmed for a 2026 SCA-partnered Idaho Corps crew position; ICC's own young-adult programs advertise weekly stipends but an org-wide figure wasn't published",
    housing_provided: 1,
    airfare_covered: 0,
    education_award: null,
    term_min_weeks: null,
    term_max_weeks: null,
    funding_status: "active",
    funding_note: "Idaho received ~$3.9M in federal AmeriCorps funding in 2026 supporting SCA and Idaho State University programs, amid the broader AmeriCorps funding turmoil nationally.",
    deadlines: [{ cycle_label: "2026 season", kind: "rolling", due_at: null, source_tz: TZ_MT, note: "Seasonal crew positions typically run spring through fall" }],
  },
  {
    slug: "wiscorps",
    name: "WisCorps",
    operator: "WisCorps, Inc. (AmeriCorps)",
    category: "conservation",
    summary:
      "Wisconsin's AmeriCorps-affiliated conservation corps runs crews of 18-30 year olds on environmental stewardship projects statewide for 3+ months, plus individual site placements. No degree required.",
    source_url: "https://wiscorps.org/",
    degree_required: 0,
    min_age: 18,
    max_age: 30,
    citizenship: "us_citizen_or_lpr",
    other_eligibility: null,
    pay_type: "weekly",
    pay_low: null,
    pay_high: null,
    pay_note: "AmeriCorps living allowance confirmed to exist; exact current figure not published. A related Great Lakes CCC AmeriCorps Veterans program in Racine, WI lists $12/hr up to 50hrs/2wks as a regional benchmark",
    housing_provided: 0,
    airfare_covered: 0,
    education_award: null,
    term_min_weeks: 13,
    term_max_weeks: null,
    funding_status: "active",
    funding_note: AMERICORPS_TURMOIL_NOTE,
    deadlines: [{ cycle_label: "2026 season", kind: "rolling", due_at: null, source_tz: TZ_CT, note: null }],
  },
  {
    slug: "maine-conservation-corps",
    name: "Maine Conservation Corps",
    operator: "Maine Dept. of Agriculture, Conservation and Forestry (Bureau of Parks and Lands)",
    category: "conservation",
    summary:
      "A state-run AmeriCorps program placing members on trail, park, and natural resource stewardship projects across Maine, with a weekly living allowance, training housing, and an education award.",
    source_url: "https://www.maine.gov/dacf/parks/get_involved/conservation_corps/index.shtml",
    degree_required: 0,
    min_age: 18,
    max_age: null,
    citizenship: "us_citizen_or_lpr",
    other_eligibility: null,
    pay_type: "weekly",
    pay_low: 27000,
    pay_high: 27000,
    pay_note: "$270/week (less taxes) confirmed for 675-hour AmeriCorps Field Team Member positions; other position types/terms may pay differently",
    housing_provided: 1,
    airfare_covered: 0,
    education_award: 225524,
    term_min_weeks: null,
    term_max_weeks: null,
    funding_status: "active",
    funding_note: null,
    deadlines: [{ cycle_label: "2026 season", kind: "rolling", due_at: null, source_tz: TZ_ET, note: null }],
  },
  {
    slug: "kansas-outdoor-americorps-action-team",
    name: "Kansas Outdoor AmeriCorps Action Team",
    operator: "Kansas Department of Wildlife & Parks",
    category: "conservation",
    summary:
      "An AmeriCorps program placing members in Kansas state parks to perform environmental service, education, and emergency-disaster-assistance projects. Living allowance paid biweekly plus an education award.",
    source_url: "https://ksoutdoors.gov/State-Parks/AmeriCorps",
    degree_required: 0,
    min_age: 18,
    max_age: null,
    citizenship: "us_citizen_or_lpr",
    other_eligibility: null,
    pay_type: "stipend_total",
    pay_low: null,
    pay_high: null,
    pay_note: "AmeriCorps living allowance and education award confirmed to exist; exact current figure could not be confirmed from publicly accessible pages",
    housing_provided: 0,
    airfare_covered: 0,
    education_award: null,
    term_min_weeks: null,
    term_max_weeks: null,
    funding_status: "active",
    funding_note: null,
    deadlines: [{ cycle_label: "2026 season", kind: "rolling", due_at: null, source_tz: TZ_CT, note: null }],
  },
  {
    slug: "southeast-conservation-corps",
    name: "Southeast Conservation Corps",
    operator: "Conservation Legacy",
    category: "conservation",
    summary:
      "A Conservation Legacy program based in Chattanooga, TN, placing young adults (18-30, up to 35 for veterans) on conservation crews across the Southeast doing trail work, urban forestry, and boundary marking.",
    source_url: "https://southeastconservationcorps.org/",
    degree_required: 0,
    min_age: 18,
    max_age: 35,
    citizenship: "us_citizen_or_lpr",
    other_eligibility: "Age cap extended to 35 for veterans (Veterans Fire Corps)",
    pay_type: "weekly",
    pay_low: 45000,
    pay_high: 65000,
    pay_note: "Ranges by crew: Urban Forestry $600/wk; Boundary Marking $550+$100/wk; Adult Camping $450+$200/wk; Veterans Fire Corps $500+$100/wk housing stipend; pre-tax, biweekly",
    housing_provided: 1,
    airfare_covered: 0,
    education_award: 281714,
    term_min_weeks: null,
    term_max_weeks: null,
    funding_status: "active",
    funding_note: null,
    deadlines: [{ cycle_label: "2026 season", kind: "rolling", due_at: null, source_tz: TZ_ET, note: null }],
  },
  {
    slug: "nevada-conservation-corps",
    name: "Nevada Conservation Corps",
    operator: "Great Basin Institute (AmeriCorps)",
    category: "conservation",
    summary:
      "An AmeriCorps environmental service program of the Great Basin Institute running trail building, fuels reduction, and restoration crews on Nevada public lands since 1999. Living stipend paid biweekly plus an education award.",
    source_url: "https://thegreatbasininstitute.org/nevada-conservation-corps/",
    degree_required: 0,
    min_age: 17,
    max_age: null,
    citizenship: "us_citizen_or_lpr",
    other_eligibility: "AmeriCorps eligibility generally requires age 17+",
    pay_type: "stipend_total",
    pay_low: null,
    pay_high: null,
    pay_note: "Living stipend confirmed; current exact figure varies by position/contract. Historical (2015) data showed $3,500-$9,500 for 3-6 month terms, likely higher today",
    housing_provided: 0,
    airfare_covered: 0,
    education_award: null,
    term_min_weeks: 12,
    term_max_weeks: 52,
    funding_status: "active",
    funding_note: null,
    deadlines: [{ cycle_label: "2026 season", kind: "rolling", due_at: null, source_tz: TZ_PT, note: null }],
  },
  {
    slug: "los-angeles-conservation-corps",
    name: "Los Angeles Conservation Corps",
    operator: "Los Angeles Conservation Corps (AmeriCorps)",
    category: "conservation",
    summary:
      "An AmeriCorps-affiliated youth corps offering paid job training in conservation, recycling, and community projects for 18-26 year olds in LA, with no high school diploma required to start (support provided to earn one while working).",
    source_url: "https://www.lacorps.org/get-involved",
    degree_required: 0,
    min_age: 18,
    max_age: 26,
    citizenship: "us_citizen_or_lpr",
    other_eligibility: "No high school diploma required; program offers diploma/GED support alongside paid work",
    pay_type: "weekly",
    pay_low: 49000,
    pay_high: null,
    pay_note: "$17.50/hour × 28 hrs/week = ~$490/week minimum; raises available at 6 and 12 months of service",
    housing_provided: 0,
    airfare_covered: 0,
    education_award: null,
    term_min_weeks: null,
    term_max_weeks: null,
    funding_status: "active",
    funding_note: null,
    deadlines: [{ cycle_label: "2026", kind: "rolling", due_at: null, source_tz: TZ_PT, note: null }],
  },
  {
    slug: "san-francisco-conservation-corps",
    name: "San Francisco Conservation Corps",
    operator: "San Francisco Conservation Corps (SFCC)",
    category: "conservation",
    summary:
      "A San Francisco nonprofit job-training and education program since 1983 for corpsmembers aged 18-26 doing landscaping, recycling, and playground renovation work. Confirmed as a currently operating paid corps.",
    source_url: "https://www.sfcc.org/",
    degree_required: 0,
    min_age: 18,
    max_age: 26,
    citizenship: "any",
    other_eligibility: null,
    pay_type: "stipend_total",
    pay_low: null,
    pay_high: null,
    pay_note: "Confirmed paid job-training corps; exact current wage was not confirmable from accessible pages during research — verify before routing students",
    housing_provided: 0,
    airfare_covered: 0,
    education_award: null,
    term_min_weeks: null,
    term_max_weeks: null,
    funding_status: "active",
    funding_note: null,
    deadlines: [{ cycle_label: "2026", kind: "rolling", due_at: null, source_tz: TZ_PT, note: null }],
  },
  {
    slug: "excelsior-conservation-corps",
    name: "New York State Excelsior Conservation Corps",
    operator: "SCA / NYS DEC / NYS OPRHP",
    category: "conservation",
    summary:
      "A residential AmeriCorps program (operated with the Student Conservation Association) placing 50 young adults ages 18-25 together for several months to restore and protect New York's parks, modeled on the original Civilian Conservation Corps.",
    source_url: "https://www.ny.gov/programs/new-york-state-excelsior-conservation-corps",
    degree_required: 0,
    min_age: 18,
    max_age: 25,
    citizenship: "us_citizen_or_lpr",
    other_eligibility: "New York State residency emphasis; special outreach to veterans",
    pay_type: "weekly",
    pay_low: 18000,
    pay_high: 18000,
    pay_note: "$180/week stipend; sources vary on program length (7 vs 10 months) reflecting changes over time",
    housing_provided: 1,
    airfare_covered: 0,
    education_award: 573000,
    term_min_weeks: 28,
    term_max_weeks: 43,
    funding_status: "active",
    funding_note: null,
    deadlines: [{ cycle_label: "2026-27", kind: "rolling", due_at: null, source_tz: TZ_ET, note: null }],
  },
  {
    slug: "florida-conservation-corps",
    name: "Florida Conservation Corps",
    operator: "Florida Department of Environmental Protection / Florida State Parks",
    category: "conservation",
    summary:
      "An AmeriCorps program managed through Florida State Parks placing members on invasive species removal, trail, and park stewardship projects statewide. Living stipend, free health insurance, and a Segal Education Award.",
    source_url: "https://www.floridastateparks.org/FLCC",
    degree_required: 0,
    min_age: 17,
    max_age: null,
    citizenship: "us_citizen_or_lpr",
    other_eligibility: "Must have a high school diploma/equivalent or be actively working toward one; valid driver's license required; 17-year-olds need parental consent",
    pay_type: "monthly",
    pay_low: 220000,
    pay_high: 220000,
    pay_note: "$2,200/month living stipend for both half-term and full-term members",
    housing_provided: 0,
    airfare_covered: 0,
    education_award: 739500,
    term_min_weeks: 26,
    term_max_weeks: 48,
    funding_status: "active",
    funding_note: "Full-term runs Sept-July (~48 wks, $7,395 award); half-term runs Jan/Feb-July (~26 wks, $3,697.50 award)",
    deadlines: [{ cycle_label: "2026-27 full term", kind: "national", due_at: null, source_tz: TZ_ET, note: "Full term runs September to July; half term runs Jan/Feb to July" }],
  },
  {
    slug: "mile-high-youth-corps",
    name: "Mile High Youth Corps",
    operator: "Mile High Youth Corps (AmeriCorps, Colorado Youth Corps Association member)",
    category: "conservation",
    summary:
      "A Colorado AmeriCorps youth corps offering land conservation, YouthBuild construction, and mentoring corpsmember positions in Denver and Colorado Springs, paying a biweekly stipend plus a Segal Education Award.",
    source_url: "https://www.milehighyouthcorps.org/",
    degree_required: 0,
    min_age: 18,
    max_age: 24,
    citizenship: "us_citizen_or_lpr",
    other_eligibility: null,
    pay_type: "weekly",
    pay_low: 56000,
    pay_high: 71000,
    pay_note: "Biweekly stipends ranged $1,120-$1,420 across roles/locations in the 2026 season (halved here to weekly); Denver Land Conservation training pay was $1,240/2wks, standard $1,160/2wks",
    housing_provided: 0,
    airfare_covered: 0,
    education_award: 517650,
    term_min_weeks: null,
    term_max_weeks: 34,
    funding_status: "at_risk",
    funding_note: "Colorado media reported 2025 DOGE-related federal cuts threatening AmeriCorps funding for Mile High Youth Corps; program was still operating and hiring as of mid-2026 per its own job postings.",
    deadlines: [{ cycle_label: "2026 season", kind: "rolling", due_at: null, source_tz: TZ_MT, note: "Example term ran April 6 – November 20, 2026 for some positions" }],
  },
  {
    slug: "michigan-civilian-conservation-corps",
    name: "Michigan Civilian Conservation Corps",
    operator: "Michigan Dept. of Natural Resources (AmeriCorps)",
    category: "conservation",
    summary:
      "A Michigan DNR AmeriCorps program for Michigan residents ages 18-27 doing forest health, pest management, and natural resource stewardship work, on a 10-hour, 4-day-week schedule plus an education award.",
    source_url: "https://www.michigan.gov/dnr/about/careers/michigan-civilian-conservation-corps-americorps-positions",
    degree_required: 0,
    min_age: 18,
    max_age: 27,
    citizenship: "us_citizen_or_lpr",
    other_eligibility: "Michigan residency required; high school diploma or GED required; some overnight travel and weekend work",
    pay_type: "weekly",
    pay_low: 68000,
    pay_high: 68000,
    pay_note: "$17/hour × 40 hours (four 10-hour days) = $680/week before tax, plus AmeriCorps education award",
    housing_provided: 0,
    airfare_covered: 0,
    education_award: null,
    term_min_weeks: null,
    term_max_weeks: null,
    funding_status: "active",
    funding_note: null,
    deadlines: [{ cycle_label: "2026 season", kind: "rolling", due_at: null, source_tz: "America/Detroit", note: null }],
  },

  // ==================== degree_required = 0, other national programs ====================
  {
    slug: "youthbuild-americorps",
    name: "YouthBuild AmeriCorps",
    operator: "YouthBuild USA (network of ~300 local programs)",
    category: "trades",
    summary:
      "A national network of community-based programs for young people 16-24 who left school without a diploma, combining paid construction/trades training (building affordable housing) with GED/diploma classroom instruction.",
    source_url: "https://youthbuild.org/",
    degree_required: 0,
    min_age: 16,
    max_age: 24,
    citizenship: "us_citizen_or_lpr",
    other_eligibility: "Applicants must have left school without a high school diploma/equivalent; program provides a GED/diploma pathway plus vocational training",
    pay_type: "monthly",
    pay_low: 52000,
    pay_high: 52000,
    pay_note: "One example local program cited a biweekly living allowance equating to up to $520/month for worksite training under a 450-hour AmeriCorps term; actual pay varies by local grantee — YouthBuild is a network of ~300 independently-operated sites, not one national payer",
    housing_provided: 0,
    airfare_covered: 0,
    education_award: null,
    term_min_weeks: 26,
    term_max_weeks: 43,
    funding_status: "active",
    funding_note: "Funded via U.S. Dept. of Labor grants plus AmeriCorps; individual local sites' funding can vary in stability.",
    deadlines: [{ cycle_label: "rolling by local program", kind: "rolling", due_at: null, source_tz: TZ_ET, note: "Applicants should find and apply to their local YouthBuild program via youthbuild.org's program locator" }],
  },
  {
    slug: "public-allies",
    name: "Public Allies AmeriCorps Program",
    operator: "Public Allies",
    category: "service",
    summary:
      "A 10-month, full-time paid AmeriCorps apprenticeship placing 'Allies' (high school diploma/GED required, no college degree needed) at nonprofit host organizations nationwide to build leadership and career skills.",
    source_url: "https://publicallies.org/americorps-program/",
    degree_required: 0,
    min_age: 17,
    max_age: null,
    citizenship: "us_citizen_or_lpr",
    other_eligibility: "High school diploma or GED required; no college degree necessary; some local programs require age 18 by program start",
    pay_type: "stipend_total",
    pay_low: 913300,
    pay_high: 2300000,
    pay_note: "Full-time (10 months): $23,000 stipend + $7,395 education award. Part-time: $9,133 stipend + $2,817.14 education award",
    housing_provided: 0,
    airfare_covered: 0,
    education_award: 739500,
    term_min_weeks: 43,
    term_max_weeks: 43,
    funding_status: "active",
    funding_note: "Received a $6.6M AmeriCorps grant to launch 288 paid apprenticeships nationally, per Public Allies' own announcement.",
    deadlines: [{ cycle_label: "2026-27 cohort", kind: "rolling", due_at: null, source_tz: TZ_CT, note: "Program typically begins in September" }],
  },
  {
    slug: "habitat-for-humanity-americorps",
    name: "Habitat AmeriCorps",
    operator: "Habitat for Humanity International",
    category: "trades",
    summary:
      "Habitat for Humanity's national AmeriCorps program places members age 18+ (high school diploma/GED, no college degree required) at local affiliates for a service year building affordable housing.",
    source_url: "https://www.habitat.org/volunteer/long-term-opportunities/americorps",
    degree_required: 0,
    min_age: 18,
    max_age: null,
    citizenship: "us_citizen_or_lpr",
    other_eligibility: "High school diploma or GED required",
    pay_type: "annual",
    pay_low: 1760000,
    pay_high: 1870000,
    pay_note: "Approximate annual living stipend, varies by site; some affiliates add local housing stipends (e.g. Bay Area affiliate adds $1,500-$1,800/month toward rent)",
    housing_provided: 0,
    airfare_covered: 0,
    education_award: 739500,
    term_min_weeks: 46,
    term_max_weeks: 52,
    funding_status: "active",
    funding_note: "Habitat for Humanity International was awarded up to $5 million in AmeriCorps funding in 2026 for continued service nationwide.",
    deadlines: [{ cycle_label: "rolling by local affiliate", kind: "rolling", due_at: null, source_tz: TZ_ET, note: "Positions posted individually by local Habitat affiliates" }],
  },
  {
    slug: "minnesota-reading-corps-math-corps",
    name: "Minnesota Reading Corps / Math Corps",
    operator: "ServeMinnesota / Ampact (AmeriCorps)",
    category: "service",
    summary:
      "AmeriCorps tutoring programs placing members in Minnesota schools to deliver literacy and math interventions to PreK-8 students. Requires only a high school diploma/GED, no prior teaching experience or college degree.",
    source_url: "https://readingandmath.org/",
    degree_required: 0,
    min_age: 18,
    max_age: null,
    citizenship: "us_citizen_or_lpr",
    other_eligibility: "High school diploma or GED required; must pass National Service criminal history checks. Full-time (35 hrs/wk) and part-time (25 or 15 hrs/wk) positions available",
    pay_type: "weekly",
    pay_low: 26250,
    pay_high: 61250,
    pay_note: "$17.50/hour; full-time ~35 hrs/week (~$612.50/wk), part-time 15 hrs/week (~$262.50/wk), for the 2026-27 school year",
    housing_provided: 0,
    airfare_covered: 0,
    education_award: 630000,
    term_min_weeks: 40,
    term_max_weeks: 44,
    funding_status: "active",
    funding_note: null,
    deadlines: [{ cycle_label: "2026-27 school year", kind: "national", due_at: null, source_tz: TZ_CT, note: "Positions run August 2026 through June 2027" }],
  },

  // ==================== degree_required = 1, fellowships ====================
  {
    slug: "princeton-in-asia",
    name: "Princeton in Asia Fellowship",
    operator: "Princeton in Asia (independent nonprofit affiliated with Princeton University)",
    category: "teaching_abroad",
    summary:
      "A one-year post-graduate fellowship placing around 60 fellows annually in paid teaching, journalism, business, or public-service placements across Asia. Open to graduating seniors and recent graduates of any university.",
    source_url: "https://www.princetoninasia.org/fellowship-faq",
    degree_required: 1,
    min_age: null,
    max_age: null,
    citizenship: "any",
    other_eligibility: "Open to graduating seniors and recent graduates of any university, not limited to Princeton; not a religious or missionary program",
    pay_type: "monthly",
    pay_low: null,
    pay_high: null,
    pay_note: "Stipend amount set per host placement to cover local cost of living; no single published dollar figure applies across all ~60 placements",
    housing_provided: 1,
    airfare_covered: 0,
    education_award: null,
    term_min_weeks: 48,
    term_max_weeks: 52,
    funding_status: "active",
    funding_note: null,
    deadlines: [{ cycle_label: "2026-27 cycle", kind: "national", due_at: null, source_tz: TZ_ET, note: "Applications for the 2026-27 fellowship year opened around September 2025; check princetoninasia.org for the current cycle deadline" }],
  },
  {
    slug: "princeton-in-africa",
    name: "Princeton in Africa Fellowship",
    operator: "Princeton in Africa (independent nonprofit affiliated with Princeton University)",
    category: "service",
    summary:
      "A one-year post-graduate fellowship placing young professionals with NGOs and other organizations working on development issues across Africa. Open to graduating seniors and recent graduates of any university.",
    source_url: "https://www.princetoninafrica.org/applicants/frequently-asked-questions/",
    degree_required: 1,
    min_age: null,
    max_age: null,
    citizenship: "any",
    other_eligibility: "Open to graduating seniors and recent graduates of any university, not limited to Princeton. Note: fellows pay a $350 placement fee plus some travel/visa/immunization costs, alongside the monthly stipend below.",
    pay_type: "monthly",
    pay_low: 35000,
    pay_high: 100000,
    pay_note: "Varies by post: ~$350/month where housing/meals/transport are provided in-kind, up to $1,000+/month in cities without in-kind support",
    housing_provided: 0,
    airfare_covered: 0,
    education_award: null,
    term_min_weeks: 48,
    term_max_weeks: 52,
    funding_status: "active",
    funding_note: null,
    deadlines: [{ cycle_label: "2026-27 cycle", kind: "national", due_at: null, source_tz: TZ_ET, note: null }],
  },
  {
    slug: "watson-fellowship",
    name: "Thomas J. Watson Fellowship",
    operator: "Watson Foundation",
    category: "research",
    summary:
      "A one-year, $40,000 stipend fellowship for graduating seniors nominated by one of 39 partner colleges, funding a year of independent, self-designed study and travel abroad with no work requirement.",
    source_url: "https://watson.foundation/fellowships/tj",
    degree_required: 1,
    min_age: null,
    max_age: null,
    citizenship: "us_citizen_or_lpr",
    other_eligibility: "Must be nominated by one of the Watson Foundation's 39 partner institutions in the same academic year the bachelor's degree is conferred; already-graduated applicants are ineligible",
    pay_type: "stipend_total",
    pay_low: 4000000,
    pay_high: 4000000,
    pay_note: "$40,000 flat stipend for the fellowship year, plus health insurance and loan-payment assistance",
    housing_provided: 0,
    airfare_covered: 0,
    education_award: null,
    term_min_weeks: 52,
    term_max_weeks: 52,
    funding_status: "active",
    funding_note: null,
    deadlines: [{ cycle_label: "2027 fellowship year", kind: "campus", due_at: null, source_tz: TZ_ET, note: "National selection begins in November; awards announced mid-March. Internal campus nomination deadlines vary by partner institution" }],
  },
  {
    slug: "luce-scholars-program",
    name: "Luce Scholars Program",
    operator: "Henry Luce Foundation",
    category: "research",
    summary:
      "A prestigious 13-month fully-funded fellowship for 16-18 young American professionals (not necessarily recent grads), placing them in individually crafted, immersive professional placements across Asia with language training.",
    source_url: "https://hluce.org/meet-the-2026-2027-luce-scholars/",
    degree_required: 1,
    min_age: null,
    max_age: 29,
    citizenship: "us_citizen_or_lpr",
    other_eligibility: "Open to young professionals up to around age 29 with limited to no prior Asia experience or Asian studies background; nominated by partner colleges/universities. Field of study is open.",
    pay_type: "stipend_total",
    pay_low: 3200000,
    pay_high: 4200000,
    pay_note: "2027-28 cohort figures: $32,000 base stipend; $38,000 for placements in Japan/South Korea/China/Taiwan; $42,000 for Singapore",
    housing_provided: 0,
    airfare_covered: 1,
    education_award: null,
    term_min_weeks: 56,
    term_max_weeks: 56,
    funding_status: "active",
    funding_note: null,
    deadlines: [{ cycle_label: "2027-28 cohort", kind: "national", due_at: null, source_tz: TZ_ET, note: "Nomination-based; check hluce.org and lucescholars.org for current-cycle campus nomination deadlines" }],
  },
];
