// Third batch: the "Gap Year Paths Compared" comparison table supplied by the
// site owner (2026-08-17), encoded verbatim as to figures.
//
// PROVENANCE WARNING — read before trusting any number in this file.
// These figures came from the owner's own compiled table, NOT from a live fetch
// of each operator's site. They have NOT been through the verify cron or a
// human confirmation pass. Every row here is seeded with last_verified_at at
// seed time but should be treated as unconfirmed until someone opens
// source_url and checks it. Deadlines are deliberately left empty rather than
// guessed: the source table had no deadline column, and a wrong deadline in
// front of a 19-year-old is the one failure that ends this project.
//
// Rows already covered by earlier batches are NOT repeated here (AmeriCorps,
// Peace Corps, Fulbright ETA, Watson, JET, TAPIF, UNC Global Gap Year).
// Two rows are re-seeded deliberately because the owner's table corrects or
// contradicts an earlier exclusion:
//   - Princeton Bridge Year: earlier batch omitted it for paying no stipend.
//     Re-added as net_neutral, which is what it actually is, now that
//     money_direction can express that.
//   - Jesuit Volunteer Corps: earlier batch excluded it as "nominal stipend".
//     The owner's table puts it at net positive ~$8-10k once room, board and
//     the Segal award are counted, which is a fair reading. Re-added as
//     participant_earns with the structure spelled out.
//
// Non-US-eligible rows (European Solidarity Corps, Germany weltwärts/FSJ) are
// included with us_eligible: 0. They are the single most common false lead
// given to American students — "why can't I do the EU one" deserves a real
// answer rather than silence.

import type { SeedProgram } from "./seed-data";

const UNVERIFIED =
  "Figure supplied by the site owner's comparison table, not yet re-confirmed against the operator's own page. Verify before relying on it.";

export const COMPARISON_TABLE_PROGRAMS: SeedProgram[] = [
  // ==================== participant pays ====================
  {
    slug: "where-there-be-dragons-se-asia",
    name: "Where There Be Dragons — Southeast Asia semester",
    operator: "Where There Be Dragons",
    category: "travel_study",
    summary:
      "An 80-day instructor-led semester in Southeast Asia running at roughly 12 students to 3 instructors. Optional college credit is available, which can make 529 funds eligible to pay for it.",
    source_url: "https://www.wheretherebedragons.com/",
    degree_required: 0,
    money_direction: "participant_pays",
    stage: "post_hs",
    min_age: 17,
    max_age: null,
    citizenship: "any",
    other_eligibility: "Application required but admission is largely open",
    selectivity: "open",
    pay_type: "none",
    pay_low: null,
    pay_high: null,
    pay_note: null,
    cost_low: 1795000,
    cost_high: 1795000,
    cost_note: "$17,950 tuition, PLUS airfare which is not included",
    housing_provided: 1,
    meals_provided: 1,
    airfare_covered: 0,
    education_award: null,
    term_min_weeks: 11,
    term_max_weeks: 12,
    college_credit_note:
      "Optional college credit is offered, which is what makes 529 funds eligible. Taking the credit is the same decision that can convert a deferred admit into a transfer applicant — check with the admissions office in writing first.",
    caveat_note: UNVERIFIED,
    funding_status: "active",
    funding_note: null,
    deadlines: [],
  },
  {
    slug: "nols-semester-rockies",
    name: "NOLS Semester in the Rockies",
    operator: "National Outdoor Leadership School (NOLS)",
    category: "outdoor",
    summary:
      "A 74-day wilderness expedition semester in the Rocky Mountains carrying 16-19 transferable academic credits. More than 400 colleges accept the University of Utah credit it grants.",
    source_url: "https://www.nols.edu/en/coursefinder/courses/semester-in-the-rockies-SRM/",
    degree_required: 0,
    money_direction: "participant_pays",
    stage: "both",
    min_age: 17,
    max_age: null,
    citizenship: "any",
    other_eligibility: "Open enrollment subject to a health screen",
    selectivity: "open",
    pay_type: "none",
    pay_low: null,
    pay_high: null,
    pay_note: null,
    cost_low: 1563000,
    cost_high: 1563000,
    cost_note: "$15,630 tuition plus a $1,000 deposit; travel to and from the course is extra",
    housing_provided: 1,
    meals_provided: 1,
    airfare_covered: 0,
    education_award: null,
    term_min_weeks: 10,
    term_max_weeks: 11,
    college_credit_note:
      "16-19 transferable credits granted through the University of Utah, accepted by 400+ colleges. Accepting credit can affect incoming-freshman aid and deferred-admit status — confirm in writing before enrolling.",
    caveat_note: UNVERIFIED,
    funding_status: "active",
    funding_note: null,
    deadlines: [],
  },
  {
    slug: "outward-bound-costa-rica-panama",
    name: "Outward Bound Costa Rica / Panama semester",
    operator: "Outward Bound",
    category: "outdoor",
    summary:
      "A 50- to 65-day expedition semester across Costa Rica and Panama with PADI dive certification included. Open enrollment subject to a health screen.",
    source_url: "https://www.outwardbound.org/",
    degree_required: 0,
    money_direction: "participant_pays",
    stage: "both",
    min_age: 17,
    max_age: null,
    citizenship: "any",
    other_eligibility: "Open enrollment subject to a health screen",
    selectivity: "open",
    pay_type: "none",
    pay_low: null,
    pay_high: null,
    pay_note: null,
    cost_low: 1390000,
    cost_high: 1850000,
    cost_note: "$13,900 for the 50-day course, $18,500 for the 65-day; PADI certification included, airfare is not",
    housing_provided: 1,
    meals_provided: 1,
    airfare_covered: 0,
    education_award: null,
    term_min_weeks: 7,
    term_max_weeks: 10,
    college_credit_note: null,
    caveat_note: `${UNVERIFIED} Owner's table notes 4 of the 6 Outward Bound entities ran deficits in FY23 — worth checking the specific entity's financial health before paying a deposit.`,
    funding_status: "active",
    funding_note: "Owner's table flags FY23 deficits across 4 of 6 Outward Bound entities.",
    deadlines: [],
  },
  {
    slug: "pg-year-boarding-school",
    name: "Postgraduate (PG) year at a boarding school",
    operator: "Various U.S. independent boarding schools",
    category: "travel_study",
    summary:
      "An extra academic year at a private boarding school after high school graduation, largely driven by athletic recruiting. Almost entirely invisible to gap year industry data.",
    source_url: "https://www.boardingschoolreview.com/",
    degree_required: 0,
    money_direction: "participant_pays",
    stage: "post_hs",
    min_age: 17,
    max_age: 20,
    citizenship: "any",
    other_eligibility: "Admission required; most placements are athletic-recruiting driven",
    selectivity: "selective",
    pay_type: "none",
    pay_low: null,
    pay_high: null,
    pay_note: null,
    cost_low: 5500000,
    cost_high: 7500000,
    cost_note: "$55,000-$75,000 for the academic year; financial aid varies widely by school",
    housing_provided: 1,
    meals_provided: 1,
    airfare_covered: 0,
    education_award: null,
    term_min_weeks: 36,
    term_max_weeks: 40,
    college_credit_note:
      "A PG year is secondary school, not college, so it does not normally create the transfer-applicant problem that college credit does. Confirm with the target college anyway.",
    caveat_note: `${UNVERIFIED} The most expensive option in this catalog by a wide margin.`,
    funding_status: "active",
    funding_note: null,
    deadlines: [],
  },
  {
    slug: "lds-mission",
    name: "LDS mission",
    operator: "The Church of Jesus Christ of Latter-day Saints",
    category: "service",
    summary:
      "An 18- to 24-month church-directed mission, self-funded at a flat monthly rate regardless of assignment location. By volume this is the largest single gap-year channel in the United States.",
    source_url: "https://www.churchofjesuschrist.org/callings/missionary",
    degree_required: 0,
    money_direction: "participant_pays",
    stage: "post_hs",
    min_age: 18,
    max_age: null,
    citizenship: "any",
    other_eligibility: "Church membership and a church-directed call; assignment location is not chosen by the participant",
    selectivity: "moderate",
    pay_type: "none",
    pay_low: null,
    pay_high: null,
    pay_note: null,
    cost_low: 1200000,
    cost_high: 1200000,
    cost_note: "Roughly $500/month, about $12,000 total over 24 months, paid by the missionary or their family",
    housing_provided: 1,
    meals_provided: 0,
    airfare_covered: 0,
    education_award: null,
    term_min_weeks: 78,
    term_max_weeks: 104,
    college_credit_note: null,
    caveat_note: `${UNVERIFIED} Owner's table cites roughly 71,000 serving and 25,000-30,000 new calls per year, making this the largest single US gap-year channel by headcount.`,
    funding_status: "active",
    funding_note: null,
    deadlines: [],
  },
  {
    slug: "masa-israel-year-course",
    name: "Masa Israel programs (e.g. Young Judaea Year Course)",
    operator: "Masa Israel Journey / Jewish Agency",
    category: "travel_study",
    summary:
      "An 8- to 10-month program in Israel, subsidized by the Israeli government and the Jewish Agency. The grant is partial, not full — participants still pay a substantial balance.",
    source_url: "https://www.masaisrael.org/",
    degree_required: 0,
    money_direction: "participant_pays",
    stage: "both",
    min_age: 18,
    max_age: 30,
    citizenship: "any",
    other_eligibility: "Open to eligible participants under Masa's criteria",
    selectivity: "open",
    pay_type: "none",
    pay_low: null,
    pay_high: null,
    pay_note: null,
    cost_low: 2150000,
    cost_high: 2850000,
    cost_note: "$31,500 list price less a $3,000-$10,000 Masa grant, so roughly $21,500-$28,500 net. Subsidy is partial, not full",
    housing_provided: 1,
    meals_provided: 0,
    airfare_covered: 0,
    education_award: null,
    term_min_weeks: 32,
    term_max_weeks: 43,
    college_credit_note: null,
    caveat_note: UNVERIFIED,
    funding_status: "active",
    funding_note: null,
    deadlines: [],
  },
  {
    slug: "rotary-youth-exchange",
    name: "Rotary Youth Exchange",
    operator: "Rotary International",
    category: "travel_study",
    summary:
      "A year abroad hosted by local Rotary clubs, with host families covering room and board. Among the best value in the sector by a wide margin.",
    source_url: "https://www.rotary.org/en/our-programs/youth-exchanges",
    degree_required: 0,
    money_direction: "participant_pays",
    stage: "post_hs",
    min_age: 15,
    max_age: 19,
    citizenship: "any",
    other_eligibility: "Selected by local Rotary clubs; availability depends on your local club",
    selectivity: "selective",
    pay_type: "none",
    pay_low: null,
    pay_high: null,
    pay_note: null,
    cost_low: 150000,
    cost_high: 300000,
    cost_note: "$1,500-$3,000 all-in for the year — host families cover room and board",
    housing_provided: 1,
    meals_provided: 1,
    airfare_covered: 0,
    education_award: null,
    term_min_weeks: 44,
    term_max_weeks: 52,
    college_credit_note: null,
    caveat_note: `${UNVERIFIED} Roughly a tenth the cost of a commercial semester abroad for a comparable length of time.`,
    funding_status: "active",
    funding_note: null,
    deadlines: [],
  },
  {
    slug: "ivhq",
    name: "IVHQ volunteer placement",
    operator: "International Volunteer HQ",
    category: "travel_study",
    summary:
      "Budget-end volunteer placements from one to twelve weeks across many countries. Open enrollment, with the participant paying both a registration fee and a weekly program fee.",
    source_url: "https://www.volunteerhq.org/",
    degree_required: 0,
    money_direction: "participant_pays",
    stage: "both",
    min_age: 18,
    max_age: null,
    citizenship: "any",
    other_eligibility: "Open enrollment",
    selectivity: "open",
    pay_type: "none",
    pay_low: null,
    pay_high: null,
    pay_note: null,
    cost_low: 28500,
    cost_high: 86400,
    cost_note:
      "$285-$864 PER WEEK plus a $329-$449 registration fee. Owner's table puts a 4-week trip all-in at $2,500-$4,000 including flights",
    housing_provided: 1,
    meals_provided: 1,
    airfare_covered: 0,
    education_award: null,
    term_min_weeks: 1,
    term_max_weeks: 12,
    college_credit_note: null,
    caveat_note: `${UNVERIFIED} Voluntourism: you are paying to perform unskilled labor. Ask what the placement would cost the host organization to hire locally, and where your fee actually goes.`,
    funding_status: "active",
    funding_note: null,
    deadlines: [],
  },
  {
    slug: "projects-abroad",
    name: "Projects Abroad",
    operator: "Projects Abroad",
    category: "travel_study",
    summary:
      "Premium-end volunteer placements at roughly $2,000 per week. The operator's own disclosure puts 24% of the fee toward recruitment and marketing and 2% toward profit.",
    source_url: "https://www.projects-abroad.org/",
    degree_required: 0,
    money_direction: "participant_pays",
    stage: "both",
    min_age: 16,
    max_age: null,
    citizenship: "any",
    other_eligibility: "Open enrollment",
    selectivity: "open",
    pay_type: "none",
    pay_low: null,
    pay_high: null,
    pay_note: null,
    cost_low: 200000,
    cost_high: 200000,
    cost_note: "Roughly $2,000 per week (from EUR1,975); airfare and insurance typically extra",
    housing_provided: 1,
    meals_provided: 1,
    airfare_covered: 0,
    education_award: null,
    term_min_weeks: 1,
    term_max_weeks: 12,
    college_credit_note: null,
    caveat_note: `${UNVERIFIED} Per the operator's own published breakdown, 24% of the fee goes to recruitment and marketing and 2% to profit. Roughly seven times IVHQ's weekly rate for a broadly similar product.`,
    funding_status: "active",
    funding_note: null,
    deadlines: [],
  },
  {
    slug: "gvi",
    name: "GVI",
    operator: "Global Vision International",
    category: "conservation",
    summary:
      "Two- to twelve-week conservation and community placements. GVI banned orphanage placements and publishes a safeguarding policy, which is not universal in this sector.",
    source_url: "https://www.gviusa.com/",
    degree_required: 0,
    money_direction: "participant_pays",
    stage: "both",
    min_age: 18,
    max_age: null,
    citizenship: "any",
    other_eligibility: "Open enrollment",
    selectivity: "open",
    pay_type: "none",
    pay_low: null,
    pay_high: null,
    pay_note: null,
    cost_low: 150000,
    cost_high: 350000,
    cost_note: "$1,500-$3,500+ per two weeks. Grants of up to 80% are advertised on conservation placements",
    housing_provided: 1,
    meals_provided: 1,
    airfare_covered: 0,
    education_award: null,
    term_min_weeks: 2,
    term_max_weeks: 12,
    college_credit_note: null,
    caveat_note: `${UNVERIFIED} Banned orphanage placements and publishes a safeguarding policy — a meaningful differentiator in a sector where neither is standard.`,
    funding_status: "active",
    funding_note: null,
    deadlines: [],
  },
  {
    slug: "earthwatch",
    name: "Earthwatch research expedition",
    operator: "Earthwatch Institute",
    category: "research",
    summary:
      "One- to two-week citizen-science expeditions assisting field researchers. The science is genuine, but the money flows the same direction as voluntourism.",
    source_url: "https://earthwatch.org/",
    degree_required: 0,
    money_direction: "participant_pays",
    stage: "both",
    min_age: 18,
    max_age: null,
    citizenship: "any",
    other_eligibility: "Open enrollment",
    selectivity: "open",
    pay_type: "none",
    pay_low: null,
    pay_high: null,
    pay_note: null,
    cost_low: 200000,
    cost_high: 450000,
    cost_note: "$2,000-$4,500 for a 1-2 week expedition; airfare typically extra",
    housing_provided: 1,
    meals_provided: 1,
    airfare_covered: 0,
    education_award: null,
    term_min_weeks: 1,
    term_max_weeks: 2,
    college_credit_note: null,
    caveat_note: `${UNVERIFIED} Funds genuine published science, which distinguishes it from most voluntourism — but the money direction is identical, and two weeks is too short to function as a gap year.`,
    funding_status: "active",
    funding_note: null,
    deadlines: [],
  },

  // ==================== net neutral ====================
  {
    slug: "princeton-novogratz-bridge-year",
    name: "Princeton Novogratz Bridge Year Program",
    operator: "Princeton University, Office of International Programs",
    category: "service",
    summary:
      "A nine-month tuition-free service year abroad for newly admitted Princeton undergraduates, who defer matriculation by one year. Princeton covers core program costs and meets full demonstrated need for related travel.",
    source_url: "https://oip.princeton.edu/our-programs/novogratz-bridge-year",
    degree_required: 0,
    money_direction: "net_neutral",
    stage: "post_hs",
    min_age: null,
    max_age: null,
    citizenship: "any",
    other_eligibility:
      "Open ONLY to students already admitted to Princeton, who apply after accepting the offer. Roughly 20-30 places. Not a post-degree fellowship.",
    selectivity: "highly_competitive",
    pay_type: "none",
    pay_low: null,
    pay_high: null,
    pay_note: "No cash stipend. Princeton covers core costs; need-based funding covers airfare, visas and immunizations.",
    cost_low: 100000,
    cost_high: 300000,
    cost_note: "$0 core program cost; roughly $1,000-$3,000 of personal incidentals over nine months",
    housing_provided: 1,
    meals_provided: 1,
    airfare_covered: 1,
    education_award: null,
    term_min_weeks: 36,
    term_max_weeks: 39,
    college_credit_note: "Financial aid is preserved across the deferral. No credit is granted, which avoids the transfer-applicant problem entirely.",
    caveat_note: `${UNVERIFIED} Net neutral rather than paid: it costs nothing but pays nothing, so it does not build savings.`,
    funding_status: "active",
    funding_note: null,
    deadlines: [],
  },
  {
    slug: "wwoof",
    name: "WWOOF (World Wide Opportunities on Organic Farms)",
    operator: "WWOOF (federated national organizations)",
    category: "work",
    summary:
      "Room and board on an organic farm in exchange for roughly four to six hours of daily labor, arranged directly with hosts. Membership costs about $45 a year in the US.",
    source_url: "https://wwoofusa.org/",
    degree_required: 0,
    money_direction: "net_neutral",
    stage: "both",
    min_age: 18,
    max_age: null,
    citizenship: "any",
    other_eligibility: "Open. Each national WWOOF organization requires its own membership.",
    selectivity: "open",
    pay_type: "none",
    pay_low: null,
    pay_high: null,
    pay_note: "No wage. Room and board are covered in exchange for 4-6 hours of daily labor.",
    cost_low: 4500,
    cost_high: 4500,
    cost_note: "About $45/year for US membership; travel to the farm is your own cost",
    housing_provided: 1,
    meals_provided: 1,
    airfare_covered: 0,
    education_award: null,
    term_min_weeks: 1,
    term_max_weeks: 52,
    college_credit_note: null,
    caveat_note: `${UNVERIFIED} This is usually NOT legal work on a tourist visa, and you have no employment rights, no workers' compensation and no recourse if a placement goes wrong. Hosts are only lightly vetted. Understand the immigration risk in the specific country before you go.`,
    funding_status: "active",
    funding_note: null,
    deadlines: [],
  },
  {
    slug: "workaway-worldpackers",
    name: "Workaway / Worldpackers",
    operator: "Workaway.info / Worldpackers",
    category: "work",
    summary:
      "Work-exchange platforms matching travelers with hosts offering room and board for labor, across more than 50,000 listings. Membership runs roughly $69-$139 a year.",
    source_url: "https://www.workaway.info/",
    degree_required: 0,
    money_direction: "net_neutral",
    stage: "both",
    min_age: 18,
    max_age: null,
    citizenship: "any",
    other_eligibility: "Open to anyone with a membership",
    selectivity: "open",
    pay_type: "none",
    pay_low: null,
    pay_high: null,
    pay_note: "No wage. Room and board in exchange for agreed hours.",
    cost_low: 6900,
    cost_high: 13900,
    cost_note: "$69-$139/year membership; travel and visas are your own cost",
    housing_provided: 1,
    meals_provided: 1,
    airfare_covered: 0,
    education_award: null,
    term_min_weeks: 1,
    term_max_weeks: 52,
    college_credit_note: null,
    caveat_note: `${UNVERIFIED} Same legal caveat as WWOOF: usually not lawful work on a tourist visa, no employment rights, no recourse. 50,000+ hosts means enormous variance in how placements are actually run.`,
    funding_status: "active",
    funding_note: null,
    deadlines: [],
  },

  // ==================== participant earns ====================
  {
    slug: "duke-gap-year-program-funding",
    name: "Duke Gap Year Program funding",
    operator: "Duke University",
    category: "service",
    summary:
      "Grants of $5,000-$15,000 — up to $25,000 with demonstrated need — for admitted Duke students taking a structured gap year. The award is taxable income.",
    source_url: "https://gapyear.duke.edu/",
    degree_required: 0,
    money_direction: "participant_earns",
    stage: "post_hs",
    min_age: null,
    max_age: null,
    citizenship: "any",
    other_eligibility:
      "Open only to admitted Duke students. Will NOT fund paid work, start-ups, blogs, or military or religious service.",
    selectivity: "selective",
    pay_type: "stipend_total",
    pay_low: 500000,
    pay_high: 2500000,
    pay_note: "$5,000-$15,000 typical, up to $25,000 with demonstrated need. Taxable income — budget for the tax.",
    cost_low: null,
    cost_high: null,
    cost_note: null,
    housing_provided: 0,
    meals_provided: 0,
    airfare_covered: 0,
    education_award: null,
    term_min_weeks: 44,
    term_max_weeks: 52,
    college_credit_note: "Deferral-based; confirm aid treatment with Duke financial aid in writing.",
    caveat_note: `${UNVERIFIED} The exclusion list matters: paid work, start-ups, blogs, and military or religious service are explicitly not fundable.`,
    funding_status: "active",
    funding_note: null,
    deadlines: [],
  },
  {
    slug: "jesuit-volunteer-corps",
    name: "Jesuit Volunteer Corps",
    operator: "Jesuit Volunteer Corps",
    category: "service",
    summary:
      "A year of full-time service with housing, food and insurance fully covered plus a small personal stipend and a Segal education award. Nets out positive once the in-kind support is counted.",
    source_url: "https://jesuitvolunteers.org/",
    degree_required: 1,
    money_direction: "participant_earns",
    stage: "post_undergrad",
    min_age: 21,
    max_age: null,
    citizenship: "us_citizen_or_lpr",
    other_eligibility: "Faith-based and service-oriented, though open beyond Catholics. Typically requires a bachelor's degree.",
    selectivity: "selective",
    pay_type: "monthly",
    pay_low: 10000,
    pay_high: 10000,
    pay_note:
      "$100/month personal stipend, PLUS full room, board and health insurance, PLUS a Segal education award. Owner's table puts the net position at roughly $8,000-$10,000 positive over the year.",
    cost_low: null,
    cost_high: null,
    cost_note: null,
    housing_provided: 1,
    meals_provided: 1,
    airfare_covered: 0,
    education_award: 619500,
    term_min_weeks: 48,
    term_max_weeks: 52,
    college_credit_note: null,
    caveat_note: `${UNVERIFIED} The $100/month headline understates it badly — room, board, insurance and the education award are the real compensation. Judge it on the net figure, not the stipend.`,
    funding_status: "active",
    funding_note: null,
    deadlines: [],
  },
  {
    slug: "schwarzman-scholars",
    name: "Schwarzman Scholars",
    operator: "Schwarzman Scholars / Tsinghua University",
    category: "research",
    summary:
      "A fully funded one-year master's at Tsinghua University in Beijing, covering tuition, housing, travel and a stipend. Took 150 of more than 5,800 applicants for 2026-27.",
    source_url: "https://www.schwarzmanscholars.org/",
    degree_required: 1,
    money_direction: "participant_earns",
    stage: "post_undergrad",
    min_age: 18,
    max_age: 28,
    citizenship: "any",
    other_eligibility: "Bachelor's degree required by program start. Ages 18-28.",
    selectivity: "highly_competitive",
    pay_type: "stipend_total",
    pay_low: null,
    pay_high: null,
    pay_note: "Full tuition, housing, travel and a personal stipend. The stipend figure itself was not in the source table — verify before publishing an amount.",
    cost_low: 0,
    cost_high: 0,
    cost_note: "$0 — fully funded",
    housing_provided: 1,
    meals_provided: 0,
    airfare_covered: 1,
    education_award: null,
    term_min_weeks: 44,
    term_max_weeks: 48,
    college_credit_note: "Confers a master's degree from Tsinghua.",
    caveat_note: `${UNVERIFIED} 150 of 5,800+ applicants for 2026-27, a 2.6% admit rate.`,
    funding_status: "active",
    funding_note: null,
    deadlines: [],
  },
  {
    slug: "teach-for-america",
    name: "Teach For America",
    operator: "Teach For America",
    category: "teaching_abroad",
    summary:
      "A two-year teaching commitment in a high-need US school district, paid a full district salary. You are employed by the district, not by TFA.",
    source_url: "https://www.teachforamerica.org/",
    degree_required: 1,
    money_direction: "participant_earns",
    stage: "post_undergrad",
    min_age: null,
    max_age: null,
    citizenship: "us_citizen_or_lpr",
    other_eligibility: "Bachelor's degree required. Placement region and subject are assigned, not chosen.",
    selectivity: "selective",
    pay_type: "annual",
    pay_low: 3200000,
    pay_high: 7200000,
    pay_note: "$32,000-$72,000 district salary depending on region, plus stipends. An extra $3,000 for Pell recipients.",
    cost_low: null,
    cost_high: null,
    cost_note: null,
    housing_provided: 0,
    meals_provided: 0,
    airfare_covered: 0,
    education_award: null,
    term_min_weeks: 104,
    term_max_weeks: 104,
    college_credit_note: null,
    caveat_note: `${UNVERIFIED} You are employed by the school district, not TFA — salary, benefits and job security follow the district's terms, not TFA's.`,
    funding_status: "active",
    funding_note: null,
    deadlines: [],
  },
  {
    slug: "nalcap-spain",
    name: "NALCAP — North American Language and Culture Assistants in Spain",
    operator: "Spanish Ministry of Education",
    category: "teaching_abroad",
    summary:
      "A seven-month English language assistantship in Spanish schools. The age cap is unusually generous, running to 44, which makes it viable well beyond the typical gap-year window.",
    source_url: "https://www.educacionfpydeportes.gob.es/eeuu/convocatorias-programas/convocatorias-eeuu/auxiliares-conversacion-eeuu.html",
    degree_required: 1,
    money_direction: "participant_earns",
    stage: "post_undergrad",
    min_age: 18,
    max_age: 44,
    citizenship: "us_citizen_or_lpr",
    other_eligibility: "US or Canadian citizen. Age cap to 44 is unusually generous for this kind of program.",
    selectivity: "moderate",
    pay_type: "monthly",
    pay_low: 80000,
    pay_high: 100000,
    pay_currency: "EUR",
    pay_note: "EUR800-1,000/month depending on region. Tight against Spanish living costs — treat it as covering costs, not building savings.",
    cost_low: null,
    cost_high: null,
    cost_note: null,
    housing_provided: 0,
    meals_provided: 0,
    airfare_covered: 0,
    education_award: null,
    term_min_weeks: 28,
    term_max_weeks: 32,
    college_credit_note: null,
    caveat_note: UNVERIFIED,
    funding_status: "active",
    funding_note: null,
    deadlines: [],
  },
  {
    slug: "australia-work-holiday-462",
    name: "Australia Work and Holiday visa (subclass 462)",
    operator: "Australian Department of Home Affairs",
    category: "work",
    summary:
      "A 12-month working holiday visa allowing Americans to work at market wages in Australia, extendable to three years. Americans must show evidence of tertiary study and are capped at age 30.",
    source_url: "https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/work-holiday-462",
    degree_required: 0,
    money_direction: "participant_earns",
    stage: "both",
    min_age: 18,
    max_age: 30,
    citizenship: "us_citizen",
    other_eligibility:
      "Americans need evidence of tertiary study. Age cap 30 — Americans were excluded from the 2026 extension to 35 that some other nationalities received.",
    selectivity: "quota_limited",
    pay_type: "hourly",
    pay_low: null,
    pay_high: null,
    pay_currency: "AUD",
    pay_note: "Market wages — Australia's minimum wage is high by US standards. Source table did not give a rate; verify the current national minimum before publishing one.",
    cost_low: null,
    cost_high: null,
    cost_note: "Visa application charge plus proof of funds; verify current amounts with Home Affairs",
    housing_provided: 0,
    meals_provided: 0,
    airfare_covered: 0,
    education_award: null,
    term_min_weeks: 52,
    term_max_weeks: 156,
    college_credit_note: null,
    caveat_note: `${UNVERIFIED} Quota-limited and age-capped at 30 for Americans. The commonly-cited extension to 35 does NOT apply to US citizens — check the official page before planning around it.`,
    funding_status: "active",
    funding_note: null,
    deadlines: [],
  },
  {
    slug: "alaska-seafood-processing",
    name: "Alaska seafood processing",
    operator: "Various Alaska processors",
    category: "work",
    summary:
      "Seasonal processing work with airfare, housing and meals all covered, paying overtime rates through long runs. Earnings depend entirely on the fish run — no fish, no hours.",
    source_url: "https://www.alaskaseafoodjobs.com/",
    degree_required: 0,
    money_direction: "participant_earns",
    stage: "both",
    min_age: 18,
    max_age: null,
    citizenship: "us_citizen_or_lpr",
    other_eligibility: "Physically demanding; drug testing and background checks are common",
    selectivity: "open",
    pay_type: "hourly",
    pay_low: 1791,
    pay_high: 2687,
    pay_note:
      "$17.91/hr regular and $26.87/hr overtime. Owner's table puts net earnings at roughly $6,000-$9,000 over a 6-week run, with airfare, housing and meals all covered.",
    cost_low: null,
    cost_high: null,
    cost_note: null,
    housing_provided: 1,
    meals_provided: 1,
    airfare_covered: 1,
    education_award: null,
    term_min_weeks: 4,
    term_max_weeks: 8,
    college_credit_note: null,
    caveat_note: `${UNVERIFIED} Hours depend entirely on the fish run — no fish means no work and no pay, and the run is not guaranteed. The high net figure comes from overtime plus zero living costs, not from the base rate.`,
    funding_status: "active",
    funding_note: null,
    deadlines: [],
  },
  {
    slug: "ski-resort-seasonal",
    name: "Ski resort seasonal work (Vail / Alterra)",
    operator: "Vail Resorts, Alterra Mountain Company, and independents",
    category: "work",
    summary:
      "A 12- to 22-week winter season at a mountain resort, paying $18-$22 an hour with a free season pass. Housing is available but deducted from pay.",
    source_url: "https://jobs.vailresortscareers.com/",
    degree_required: 0,
    money_direction: "participant_earns",
    stage: "both",
    min_age: 18,
    max_age: null,
    citizenship: "us_citizen_or_lpr",
    other_eligibility: "Most roles need no experience; some need certification",
    selectivity: "open",
    pay_type: "hourly",
    pay_low: 1800,
    pay_high: 2200,
    pay_note:
      "$18-$22/hr. Owner's table puts net at roughly $5,000-$7,000 over a 12-week season AFTER the $300-$600/month housing deduction. Free season pass included.",
    cost_low: null,
    cost_high: null,
    cost_note: "Employee housing is deducted from pay at roughly $300-$600/month, not provided free",
    housing_provided: 0,
    meals_provided: 0,
    airfare_covered: 0,
    education_award: null,
    term_min_weeks: 12,
    term_max_weeks: 22,
    college_credit_note: null,
    caveat_note: `${UNVERIFIED} Housing is deducted, not free — the headline hourly rate overstates take-home. Net out at roughly $5,000-$7,000 for a 12-week season.`,
    funding_status: "active",
    funding_note: null,
    deadlines: [],
  },
  {
    slug: "national-park-concessioner",
    name: "National park concessioner (Xanterra and peers)",
    operator: "Xanterra Travel Collection and other NPS concessioners",
    category: "work",
    summary:
      "Seasonal hospitality work inside national parks, with mandatory room and board deducted weekly. The lowest-paying option in this tier, chosen mostly for the setting.",
    source_url: "https://www.xanterra.com/careers/",
    degree_required: 0,
    money_direction: "participant_earns",
    stage: "both",
    min_age: 18,
    max_age: null,
    citizenship: "us_citizen_or_lpr",
    other_eligibility: "Most roles need no experience",
    selectivity: "open",
    pay_type: "hourly",
    pay_low: 1050,
    pay_high: 1370,
    pay_note:
      "$10.50-$13.70/hr plus tips in some roles. Owner's table puts net at roughly $3,500-$4,500 over 12 weeks after the mandatory $110-$130/week room and board.",
    cost_low: null,
    cost_high: null,
    cost_note: "Mandatory room and board of roughly $110-$130/week is deducted from pay",
    housing_provided: 0,
    meals_provided: 0,
    airfare_covered: 0,
    education_award: null,
    term_min_weeks: 12,
    term_max_weeks: 26,
    college_credit_note: null,
    caveat_note: `${UNVERIFIED} Room and board are mandatory and deducted, and cell service is limited or absent at many locations. Lowest net earnings of the seasonal-work tier.`,
    funding_status: "active",
    funding_note: null,
    deadlines: [],
  },
  {
    slug: "au-pair-usa-j1",
    name: "Au pair in the United States (J-1)",
    operator: "State Department-designated J-1 sponsors",
    category: "work",
    summary:
      "Live-in childcare on a J-1 visa for twelve months, extendable, with room, board and a $500 education allowance on top of a weekly stipend. The federal stipend floor has not moved since 2009.",
    source_url: "https://j1visa.state.gov/programs/au-pair",
    degree_required: 0,
    money_direction: "participant_earns",
    stage: "both",
    min_age: 18,
    max_age: 26,
    citizenship: "any",
    other_eligibility: "For FOREIGN nationals coming to the US — not a route for Americans to work abroad. Requires a designated sponsor.",
    selectivity: "open",
    pay_type: "weekly",
    pay_low: 19575,
    pay_high: 19575,
    pay_note:
      "$195.75/week federal floor, roughly $10,179/year, PLUS room, board and a $500 education allowance. Higher floors apply in California, New York and Washington.",
    cost_low: null,
    cost_high: null,
    cost_note: null,
    housing_provided: 1,
    meals_provided: 1,
    airfare_covered: 0,
    education_award: 50000,
    term_min_weeks: 52,
    term_max_weeks: 104,
    college_credit_note: null,
    caveat_note: `${UNVERIFIED} The federal stipend floor is tied to the $7.25 minimum wage and has been unchanged since 2009. Note this is an INBOUND program for foreign nationals; Americans wanting to au pair abroad need a different route.`,
    funding_status: "active",
    funding_note: null,
    deadlines: [],
  },
  {
    slug: "yacht-crew",
    name: "Yacht crew (after STCW certification)",
    operator: "Private and charter yacht industry",
    category: "work",
    summary:
      "Live-aboard crew work paying $1,500-$2,500 a month with zero housing or food costs. Requires STCW certification costing $900-$2,800 upfront, typically recovered within one to two months.",
    source_url: "https://www.maritime.dot.gov/",
    degree_required: 0,
    money_direction: "participant_earns",
    stage: "both",
    min_age: 18,
    max_age: null,
    citizenship: "any",
    other_eligibility: "STCW Basic Safety Training required before hiring; ENG1 or equivalent medical usually required",
    selectivity: "open",
    pay_type: "monthly",
    pay_low: 150000,
    pay_high: 250000,
    pay_note: "$1,500-$2,500/month living aboard, so nearly all of it is savable. Tips can add substantially on charter boats.",
    cost_low: 90000,
    cost_high: 280000,
    cost_note: "STCW certification costs $900-$2,800 upfront, typically recovered in 1-2 months of work. Travel to a yachting hub is extra.",
    housing_provided: 1,
    meals_provided: 1,
    airfare_covered: 0,
    education_award: null,
    term_min_weeks: 12,
    term_max_weeks: 52,
    college_credit_note: null,
    caveat_note: `${UNVERIFIED} Requires real upfront capital ($900-$2,800) and travel to a hub like Fort Lauderdale or Antibes with no guarantee of placement. Zero living costs while aboard is what makes the modest salary attractive.`,
    funding_status: "active",
    funding_note: null,
    deadlines: [],
  },
  {
    slug: "work-and-save-at-home",
    name: "Work and save at home",
    operator: "No operator — the DIY path",
    category: "work",
    summary:
      "Take a local job, live cheaply, and bank the difference. Statistically the majority path for American students taking time off, and invisible to every gap-year dataset.",
    source_url: "https://www.bls.gov/",
    degree_required: 0,
    money_direction: "participant_earns",
    stage: "both",
    min_age: 16,
    max_age: null,
    citizenship: "any",
    other_eligibility: "None",
    selectivity: "open",
    pay_type: "hourly",
    pay_low: 1600,
    pay_high: 1600,
    pay_note: "$16/hr typical. Owner's table puts net at roughly $2,000-$2,500 per four weeks BEFORE rent — the savings rate depends entirely on whether you are paying rent.",
    cost_low: null,
    cost_high: null,
    cost_note: null,
    housing_provided: 0,
    meals_provided: 0,
    airfare_covered: 0,
    education_award: null,
    term_min_weeks: 1,
    term_max_weeks: 52,
    college_credit_note:
      "If you take college courses during the year, earning credit can forfeit incoming-freshman aid and merit awards, and can convert a deferred admit into a transfer applicant. Audit the course or confirm with admissions in writing first.",
    caveat_note: `${UNVERIFIED} The statistical majority path and the benchmark every other option should be measured against. If a program costs $17,950 and this nets $2,000/month, the real question is what the program buys you that 9 months of savings does not.`,
    funding_status: "active",
    funding_note: null,
    deadlines: [],
  },

  // ============ not available to US citizens — indexed on purpose ============
  {
    slug: "european-solidarity-corps",
    name: "European Solidarity Corps",
    operator: "European Commission",
    category: "service",
    summary:
      "An EU-funded service year covering travel, board and insurance plus monthly pocket money. Open only to EU citizens and residents — there is no US equivalent.",
    source_url: "https://youth.europa.eu/solidarity_en",
    degree_required: 0,
    money_direction: "participant_earns",
    stage: "both",
    min_age: 18,
    max_age: 30,
    citizenship: "any",
    us_eligible: 0,
    other_eligibility:
      "EU citizens and legal residents only. US citizens are NOT eligible. Listed here because it is frequently and wrongly recommended to Americans.",
    selectivity: "open",
    pay_type: "monthly",
    pay_low: 15000,
    pay_high: 50000,
    pay_currency: "EUR",
    pay_note: "EUR150-500/month pocket money on top of covered travel, board and insurance. Net cost to participant is zero.",
    cost_low: 0,
    cost_high: 0,
    cost_note: "$0 — travel, board and insurance covered",
    housing_provided: 1,
    meals_provided: 1,
    airfare_covered: 1,
    education_award: null,
    term_min_weeks: 8,
    term_max_weeks: 52,
    college_credit_note: null,
    caveat_note: `${UNVERIFIED} EUR129.6M budgeted for 2026. No US equivalent exists — the closest American analogue is AmeriCorps, which is domestic-only and less generously funded per participant.`,
    funding_status: "active",
    funding_note: null,
    deadlines: [],
  },
  {
    slug: "germany-weltwaerts-fsj",
    name: "Germany weltwärts / FSJ",
    operator: "German Federal Ministry for Economic Cooperation and Development (BMZ)",
    category: "service",
    summary:
      "German government-funded voluntary service years paying monthly pocket money with costs covered. Open to German citizens and residents only.",
    source_url: "https://www.weltwaerts.de/",
    degree_required: 0,
    money_direction: "participant_earns",
    stage: "both",
    min_age: 18,
    max_age: 28,
    citizenship: "any",
    us_eligible: 0,
    other_eligibility:
      "German citizens and residents only. US citizens are NOT eligible. Listed because it is often cited as a model the US lacks.",
    selectivity: "selective",
    pay_type: "monthly",
    pay_low: 30000,
    pay_high: 50000,
    pay_currency: "EUR",
    pay_note: "EUR300-500/month pocket money under FSJ, with costs covered. Net cost to participant is zero.",
    cost_low: 0,
    cost_high: 0,
    cost_note: "$0 net — BMZ funds up to 75% of sending-organization costs",
    housing_provided: 1,
    meals_provided: 1,
    airfare_covered: 1,
    education_award: null,
    term_min_weeks: 26,
    term_max_weeks: 78,
    college_credit_note: null,
    caveat_note: `${UNVERIFIED} Not open to Americans.`,
    funding_status: "active",
    funding_note: null,
    deadlines: [],
  },
];
